Adding additional French translations
cds-snc/saas-procurement pull request #117
Opened 2023-05-10 18:17 UTC by sylviamclaughlin

# Summary | Résumé

Adding additional translations to make the app fully bilingual.

2023-05-11 01:52 UTC, gcharest requested changes
I reviewed the strings and while I'm comfortable with some of the proposed changes, I'd probably request support from the translation services team 😄 

I'm also not sure how we can change the terms in a way that uses inclusive writing.

2023-05-11 01:52 UTC, gcharest commented on saas_app/locale/fr/LC_MESSAGES/django.po
> +msgstr "Date d'envoi à l'approbateur S32"
I'm not 100% sure what's the French word for this? I think it's the right one though :)

2023-05-11 01:52 UTC, gcharest commented on saas_app/locale/fr/LC_MESSAGES/django.po
> +msgstr "Date à laquelle le responsable a examiné la demande"
respsable -> approbateur S32

2023-05-11 01:52 UTC, gcharest commented on saas_app/locale/fr/LC_MESSAGES/django.po
> +msgstr "Le responsable a approuvé la demande"
le responsable -> l'approbateur S32

2023-05-11 01:52 UTC, gcharest commented on saas_app/locale/fr/LC_MESSAGES/django.po
> +msgstr "Gestionnaire approuvé"
I think we could use "Approuvé par le gestionnaire"

2023-05-11 01:52 UTC, gcharest commented on saas_app/locale/fr/LC_MESSAGES/django.po
> +msgstr "Gestionnaire refusé"
If we change the one before, we could say "Refusé par le gestionnaire"

2023-05-11 01:52 UTC, gcharest commented on saas_app/locale/fr/LC_MESSAGES/django.po
>  msgstr "Informations sur la date demandées"
I think the French syntax might be something like:
"Date à laquelle des informations ont été demandées"

That said, I haven't seen this string in the UI

2023-05-11 01:52 UTC, gcharest commented on saas_app/locale/fr/LC_MESSAGES/django.po
>  msgstr "Centre de fonds"
I'd have to check with official documentation as I'm not sure it's the same term used in French

2023-05-11 01:52 UTC, gcharest commented on saas_app/locale/fr/LC_MESSAGES/django.po
> +msgstr "Approbateur S32 approuvé"
I think the syntax might be: "Approuvé par l'approbateur S32"

Although that does sound a bit odd...

2023-05-11 01:52 UTC, gcharest commented on saas_app/locale/fr/LC_MESSAGES/django.po
>  "l'approbateur ou au demandeur S32"
I think this last part probably is more along those lines:
"l'approbateur S32 ou au demandeur"

2023-05-11 14:54 UTC, sylviamclaughlin commented
@gcharest - I have made all the changes! Thank you for reviewing the translations

2023-05-15 20:01 UTC, gcharest approved these changes
Approved! I'd recommend another review by Translation Services whenever possible for a better consistency with the terms used 😄

2023-05-15 20:05 UTC, merged